### ISSUE TITLE
Gem: pivotal tracker product manager

### ISSUE THREAD

**Issue by an-ju** [an-ju/projectscope#14]
Write a gem that shows about the product manager practice.

**Comment by hrzlvn** [comment]
Could you be more specific? I don't see any attributes of the project shown on Pivotal Tracker has something to do with the PM practice. If it is an evaluation model need to be built, let us know how you would evaluate PM practice.

**Comment by an-ju** [comment]
The practice we want to measure here is that there should be only one product manager within each iteration. The product manager should be in charge of accepting and delivering stories.

This will be a bar chart of the number of accepting and delivering transitions performed by each students.

**Comment by an-ju** [comment]
Use this repo: https://github.com/an-ju/project_metric_story_manage for development.

Tell me to add you as collaborator before you start.

**Comment by an-ju** [comment]
Closed.
