### ISSUE TITLE
Gem: story points estimation

### ISSUE THREAD

**Issue by an-ju** [an-ju/projectscope#15]
Write a gem that shows the correlation between story points and "real" workload.

**Comment by hrzlvn** [comment]
Story points can be accessed easily by the API of PivotalTracker, but how would you estimate the real workload? Given the amount of programming work is really hard to quantify.

**Comment by an-ju** [comment]
This is a scatter plot with
X-axis: the point estimation
Y-axis: workload

Workload can be calculated as the time between "started" and "finished" of the story. This relies on a correct use of story and considers only time information. But I think it is a good starting point.

**Comment by an-ju** [comment]
Use this repo: https://github.com/an-ju/project_metric_point_estimation for development.

**Comment by an-ju** [comment]
Merged in PR #20 .
