### ISSUE TITLE
Fix the layout with Boostrap

### ISSUE THREAD

**Issue by an-ju** [an-ju/projectscope#5]
The layout now has to be set manually. With Boostrap, the view can be made more beautiful.

**Comment by stevenwuyinze** [comment]
Using bootstrap indeed improves the visual effects in the long run. However, the first step, I think, should be drawing a blueprint on how the new design should look like (as I believe any existing bootstrap [template](http://getbootstrap.com/examples/theme/) doesn't fit our philosophy). Do you want to first do the design so we can discuss it over meeting of this week?

**Comment by an-ju** [comment]
Agree! I start with this because I can't bear the very ugly and chaotic layout as it is now. But yes I'll come up with a design and discuss with you this week.

**Comment by an-ju** [comment]
Updated partly with PR #11 .

**Comment by an-ju** [comment]
Updated with Booswatch in PR #33 .
