### ISSUE TITLE
Privilege control

### ISSUE THREAD

**Issue by an-ju** [an-ju/projectscope#59]
Add more comprehensive privilege control for production.

**Comment by stevenwuyinze** [comment]
My thought on this is to use "cancan" as the privilege manager. The current devise gem doesn't come in as handy as cancan.

**Comment by an-ju** [comment]
Oh, hi Steven! Right the system is running with cancan now (I added it in PR #38 ). This issue is a reminder for myself that current privilege control system is not comprehensive enough, since some new features have been added since then.

**Comment by an-ju** [comment]
Merged in PR #63 .
