### ISSUE TITLE
Bug: miss matched parameters.

### ISSUE THREAD

**Issue by an-ju** [an-ju/projectscope#6]
When creating/updating a new project, the parameters will mismatch. For example, token parameter for PivotalTracker will go to GitHub instead.

**Comment by an-ju** [comment]
How to replicate: update a project.

**Comment by stevenwuyinze** [comment]
I notice your update in view, please pin that commit to here.

The current implementation correctly displays users' input and have correct interaction with database. However when the input value get parsed and save into database, unnecessary delimiters and characters are included, although they are not shown in the html.

How to replicate: setting a debugger in project#update. The params the controller takes in have incorrectly parsed credential hash.

**Comment by an-ju** [comment]
@stevenwuyinze I'm not sure which view update you're talking about. I updated the index page with [this commit](https://github.com/an-ju/projectscope/commit/8704528eb10f1dad42d6721f4f76e25cfc61439a).

Any idea how can we solve this delimiter problem?

**Comment by an-ju** [comment]
Fixed with PR #25 .
