### ISSUE TITLE
Bug: figures not plotted

### ISSUE THREAD

**Issue by an-ju** [an-ju/projectscope#8]
Sometimes the figure is not plotted. I think this is due to the event that the call of the drawing function is attached to.

**Comment by stevenwuyinze** [comment]
I am not sure which figure is not plotting. Can you please provide how to replicate the bug?

**Comment by an-ju** [comment]
How to replicate: update a project.

**Comment by stevenwuyinze** [comment]
Get it. The associated routes is incorrect. Will fix it this week.

**Comment by an-ju** [comment]
Thanks!

**Comment by an-ju** [comment]
@stevenwuyinze any progress?

**Comment by an-ju** [comment]
I think this is due to the way plotting function is called. It's fixed now.
