### ISSUE TITLE
Bug: Fix timeline selection

### ISSUE THREAD

**Issue by an-ju** [an-ju/projectscope#9]
Currently, the timeline selection function is broken.

**Comment by an-ju** [comment]
How to replicate: move the timeline selection button.

**Comment by stevenwuyinze** [comment]
The underlying JS function for timeline is broken after we change the view. I am sure that more abstraction on retrieving data on specific dates is needed. @harrytflv, do you have any idea on how to fix this?

**Comment by stevenwuyinze** [comment]
The underlying JS function for timeline is broken after we change the view. I am sure that more abstraction on retrieving data on specific dates is needed. @harrytflv, do you have any idea on how to fix this?

**Comment by an-ju** [comment]
Fixed in branch cc2b4f72b6a22beca0dc671627b2890fec8bae72.
